Dev
nekitboy/JS-for-Enterprise-Development pull request #4
Opened 2018-09-21 16:31 UTC by nekitboy

Weak 2

2018-09-21 16:46 UTC, AVVlasov commented on webpack.config.js
> +        defaultapp: ['./stub/js/script.js']
тут должно быть defaultapp: ['./src/index.js']
папка stub для заглушек

2018-09-21 16:54 UTC, nekitboy commented on webpack.config.js
> +        defaultapp: ['./stub/js/script.js']
Обязательно скрипт должен называться index,js?
Это потому что это основной скрипт и все остальные через него должны подключаться?
Или каждый скрипт мы как отдельное `entry` подключаем?

2018-09-21 17:31 UTC, nekitboy reviewed
@AVVlasov , please check new commit

2018-09-24 19:48 UTC, kos33rd requested changes
Нужен `package.json` файл.
Также необходимо проверить, что дев-сервер запускается без необходимости глобальной установки `nodemon`

2018-09-26 14:12 UTC, AVVlasov commented on webpack.config.js
> +        defaultapp: ['./stub/js/script.js']
тут указывается точка входа, в клиентское приложение, index.js это общепринятый файлик по умолчанию, но можно и другой файл указать

2018-11-01 12:18 UTC, nekitboy commented
Reconfigured development environment

2018-11-02 18:09 UTC, kos33rd approved these changes
Отлично, с package.json и nodemon всё в порядке, апрув.

2018-11-02 19:19 UTC, merged